name: Build and test PSA page with Eleventy

on:
    workflow_dispatch:
    push:
        branches:
            - main
    
jobs:
    build_and_test:
        runs-on: ubuntu-latest
        steps:
          - name: checkout
            uses: actions/checkout@v4

          - name: use_node
            uses: actions/setup-node@v3
            with:
              node-version: '20.x'

          - name: Install dependencies
            run: npm ci

          - name: Build code
            run: npm run build --if-present

          - name: Cypress tests
            uses: cypress-io/github-action@v6

          # bump version here